package kr.hs.dgsw.where_corona.data.model.response_model

data class CoronaInfo(
    val NowCase: String,
    val TodayDeath: String,
    val TodayRecovered: String,
    val TotalCase: String,
    val TotalCaseBefore: String,
    val TotalChecking: String,
    val TotalDeath: String,
    val TotalRecovered: String,
    val caseCount: String,
    val casePercentage: String,
    val checkingCounter: String,
    val checkingPercentage: String,
    val city1n: String,
    val city1p: String,
    val city2n: String,
    val city2p: String,
    val city3n: String,
    val city3p: String,
    val city4n: String,
    val city4p: String,
    val city5n: String,
    val city5p: String,
    val deathPercentage: Double,
    val notcaseCount: String,
    val notcasePercentage: String,
    val recoveredPercentage: Double,
    val resultCode: String,
    val resultMessage: String,
    val source: String,
    val updateTime: String
)